.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "OSU" "1" "February 2013" "" ""
.
.SH "NAME"
\fBosu\fR \- Ruby rules\-based automated build tool
.
.SH "SYNOPSIS"
\fBosu\fR \fBosu\fR \fIbookmark\fR [\fIarg\fR\.\.\.]
.
.br
\fBosu\fR \fB\-R\fR|\fB\-\-rules\fR
.
.br
\fBosu\fR \fB\-h\fR|\fB\-\-help\fR
.
.br
.
.SH "DESCRIPTION"
\fBOsu\fR is an \fIautological\fR build tool, in that it is used to automate build procedure via logical rules\-based programming\. The developer only ever needs to run a single command, \fBosu\fR, and the majority of maintenance details of a project are handled\. Osu largely replaces the need of more traditional task\-based build tools, but it does not complete supplant them\. They reamin a useful complement for one\-off manual build procedures\.
.
.SH "OPTIONS"
These options act as subcommands:
.
.TP
\fB\-R\fR, \fB\-\-rules\fR
Display the described rules defined in the project\'s osu script(s)\.
.
.TP
\fB\-h\fR, \fB\-\-help\fR
Display this help message\.
.
.SH "ISSUES"
\fBOsu\fR depends on \fBRonn\fR to provide this man\-page and command help message\. Ronn depends on hpricot and rdiscount, extension libraries that are non\-trivial to install on some systems\. A more portable version of this program would be welcome\.
.
.SH "COPYRIGHT"
Osu is Copyright (c) 2009 Thomas Sawyer, Rubyworks
.
.P
Osu is distributed in accordance to the \fBGPL\-3\fR license\.
.
.SH "SEE ALSO"
ronn(1), rake(1)
