#!mast .ruby .yardopts bin eg lib man qed spec test [A-Z]*.*
.ruby
.yardopts
bin/ou
lib/ousama/command.rb
lib/ousama/digest.rb
lib/ousama/file_logic.rb
lib/ousama/rc.rb
lib/ousama/rulefile.rb
lib/ousama/session.rb
lib/ousama/system.rb
lib/ousama.rb
man/ou.1
man/ou.1.html
man/ou.1.ronn
qed/overview.rdoc
HISTORY.rdoc
README.rdoc
