#!/usr/bin/env ruby

name         'ousama'
version      '0.1.0'
title        'Ousama'
summary      'Build On Demand'
created      '2010-01-01'
description  'Ousama is a continuous integration tool with a powerful rules system.'
authors      'trans <transfire@gmail.com>'
requirements 'qed (test)'
organization 'rubyworks'
copyrights   '(c) 2010 Thomas Sawyer, Rubyworks'
repositories 'upstream' => 'git://github.com/rubyworks/ousama.git'
resources    'website' => 'http://rubyworks.github.com/ousama'
             'issues'  => 'http://rubyworks.github.com/ousama/issues'

