require 'fileutils'
require 'ostruct'
require 'notify'

require_relative 'fire/core_ext'
require_relative 'fire/match'
require_relative 'fire/shellutils'
require_relative 'fire/state'
require_relative 'fire/rule'
require_relative 'fire/digest'
require_relative 'fire/session'
require_relative 'fire/system'
require_relative 'fire/runner'
require_relative 'fire/cli'
